[target.thumbv7em-none-eabihf]
runner = "sh -c 'echo \"cargo run is not supported for this crate. Use make firmware to build.\"; exit 1'"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
